version: '3'
services:

  php:
    container_name: testapi_php
    build:
      context: docker/php
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - .:/var/www/public

  nginx:
    container_name: testapi_nginx
    build:
      context: docker/nginx
    ports:
      - 8081:80
      - 8082:443
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/log:/var/log/nginx
      - .:/var/www/public
      - ./docker/nginx/certs:/etc/nginx/certs